### ISSUE TITLE
setsockopt failed when encrypting key

### ISSUE THREAD

**Issue by Oquirella** [f-secure-foundry/mxs-dcp#4]
The following error occurs when trying to encrypt a key:

dcp_tool enc /boot/luks/rootfs.key-tmp /boot/luks/rootfs.key 00 (1): dcp_tool: enc /boot/luks/rootfs.key-tmp to /boot/luks/rootfs.key
dcp_tool: deriving key, diversifier 00
dcp_tool: error, setsockopt failed

dmesg only shows:
[  848.857322] mxs_dcp: loading out-of-tree module taints kernel.

Go version: 1.12
Kernel version: 5.4.123

**Comment by andrejro** [comment]
Please try using the just pushed `longterm-5.4` branch.

**Comment by andrejro** [comment]
Was the `CONFIG_CRYPTO_DEV_MXS_DCP` option enabled as built-in or as a module?

**Comment by Oquirella** [comment]
As built-in

**Comment by andrejro** [comment]
Documentation updated: https://github.com/f-secure-foundry/mxs-dcp/commit/381a3280c6d9a1083cd5a6b4b2e9abbb252711c8
