### ISSUE TITLE
Encryption keys are extractable

### ISSUE THREAD

**Issue by meehow** [f-secure-foundry/mxs-dcp#5]
Let's discuss [in one place](https://github.com/f-secure-foundry/interlock/issues/50), but is very similar code in 3 repos.

**Comment by abarisani** [comment]
See the discussion in the linked issue.

Additionally for this project the mxs-dcp driver is a mere port of the original Freescale one to use the internal OTPMK key without it being exposed.

The `dcp_tool.go` example is merely a reference example which clearly states:

```
// Symmetric file encryption using AES-128-OFB, key is derived from a known
// diversifier encrypted with AES-128-CBC through the NXP Data Co-Processor
// (DCP) with its device specific secret key. This uniquely ties the derived
// key to the specific hardware unit being used.
```

So again no claim is being made that the derived key is kept within hardware, but just that it's used to tie a derived key on the specific hardware unit.

The execution context of the tool is irrelevant for the scope of the example.
